#!/usr/bin/env bash

install() {
    shift
    cd bin
    ./install.sh $@
}

installMulti() {
    shift
    cd bin
    ./install-multiple.sh $@
}

update() {
    shift
    cd bin
    ./update.sh $@
}

delete() {
    shift
    cd bin
    ./delete.sh $@
}

hosts() {
    shift
    cd bin
    ./hosts-update.sh $@
}

run() {
    shift
    vboxmanage startvm $@ --type headless
}

halt() {
    shift
    vboxmanage controlvm $@ poweroff
}

usage() {
    shift
    echo "deploy add --name=... --ip=... [--cpu=nb --ram=nb (mb)]"
    echo "deploy multiple-add <file>"
    echo "deploy update"
    echo "deploy update-hosts"
    echo "deploy remove --name=..."
    echo "deploy start <name>"
    echo "deploy halt <name>"
    echo "deploy help"
}

# Check if they are at least 1 param
if [[ $# -eq 0 ]]; then # Error, no args provided
    usage
    exit 1
fi

# Filter the first arg
case $1 in
    add)
        install "$@"
        ;;
    multiple-add)
        installMulti "$@"
        ;;
    update)
        update "$@"
        ;;
    remove)
        delete "$@"
        ;;
    update-hosts)
        hosts "$@"
        ;;
    help)
        usage
         ;;
    start)
        run "$@"
         ;;
    halt)
        halt "$@"
         ;;
    *)
        echo "ERROR: unknown parameter \"$1\""
        usage
        exit 1
        ;;
esac
