#!/usr/bin/env bash

install() {
    ./install.sh $@
}

update() {
    ./update.sh $@
}

delete() {
    ./delete.sh $@
}

hosts() {
    ./hosts-update.sh $@
}

usage() {
    echo "Create a VM : deploy add --name=... --ip=... [--cpu=nb --ram=nb (mb)]"
    echo "Update all the VMs : deploy update"
    echo "Delete a VM : deploy remove --name=..."
    echo "Help : deploy help"
}

# Check if they are at least 1 param
if [[ $# -eq 0 ]]; then # Error, no args provided
    usage
    exit 1
fi

# Filter the first arg
case $1 in
    add)
        shift
        install "$@"
        ;;
    update)
        update "$@"
        ;;
    remove)
        delete "$@"
        ;;
    update-hosts)
        hosts "$@"
        ;;
    help)
        usage
         ;;
    *)
        echo "ERROR: unknown parameter \"$PARAM\""
        usage
        exit 1
        ;;
esac
